=== SDARG/opendse/opendse/opendse-io/src/main/resources/schema/schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns="http://opendse.sourceforge.net" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://opendse.sourceforge.net" elementFormDefault="qualified">

	<xs:element name="specification">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="architecture" />
				<xs:element ref="application" />
				<xs:element ref="mappings" />
				<xs:element ref="routings" minOccurs="0" />
				<xs:element ref="attributes" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
		<!-- rules for cross references using the IDs -->
		<!-- the source of a mapping must be a valid task ID -->
		<xs:keyref name="mappingTotaskRef" refer="taskUniq">
			<xs:selector xpath=".//mapping" />
			<xs:field xpath="@source" />
		</xs:keyref>
		<!-- the target of a mapping must be a valid resource ID -->
		<xs:keyref name="mappingToResourceRef" refer="resourceUniq">
			<xs:selector xpath=".//mapping" />
			<xs:field xpath="@target" />
		</xs:keyref>
		<!-- the source of a routing must be a valid communication ID -->
		<xs:keyref name="routingToCommunicationRef" refer="communicationUniq">
			<xs:selector xpath=".//routing" />
			<xs:field xpath="@source" />
		</xs:keyref>
	</xs:element>

	<!-- each object may have attributes, containing an arbitrary number of 
		attribute elements -->
	<xs:element name="attributes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- an attribute has a name and a type, which defines how to parse its 
		content -->
	<xs:element name="attribute">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="name" type="xs:string" use="required" />
					<xs:attribute name="type" use="required"> <!-- type of attributes -->
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="DOUBLE" />
								<xs:enumeration value="INT" />
								<xs:enumeration value="STRING" />
								<xs:enumeration value="BOOL" />
								<!-- more types may be added -->
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="parameter"> <!-- optional type of parameter definition -->
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="SELECT" />
								<xs:enumeration value="RANGE" />
								<xs:enumeration value="UID" />
								<!-- more parameter types may be added -->
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<!-- the architecture models the hardware topology -->
	<xs:element name="architecture">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="resource" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="link" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
		<!-- resource IDs are unique -->
		<xs:key name="resourceUniq">
			<xs:selector xpath="resource" />
			<xs:field xpath="@id" />
		</xs:key>
		<!-- link IDs are unique -->
		<xs:key name="linkUniq">
			<xs:selector xpath="link" />
			<xs:field xpath="@id" />
		</xs:key>
		<!-- the source of a link must be a valid task ID -->
		<xs:keyref name="resourceToLinkRef" refer="resourceUniq">
			<xs:selector xpath=".//link" />
			<xs:field xpath="@source" />
		</xs:keyref>
		<!-- the destination of a link must be a valid task ID -->
		<xs:keyref name="linkToResourceRef" refer="resourceUniq">
			<xs:selector xpath=".//link" />
			<xs:field xpath="@destination" />
		</xs:keyref>
	</xs:element>

	<!-- the resource is a hardware entity -->
	<xs:element name="resource">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attributes" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- the link is a directed or undirected communication ability between 
		two resources -->
	<xs:element name="link">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attributes" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="source" type="xs:string" use="required" />
			<xs:attribute name="destination" type="xs:string" use="required" />
			<xs:attribute name="orientation" use="required"> <!-- orientation of links and dependencies -->
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="DIRECTED" />
						<xs:enumeration value="UNDIRECTED" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<!-- the application models the logical functions of the system, the functions 
		consist of tasks, communications and their dependencies -->
	<xs:element name="application">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="task" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="communication" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="dependency" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="functions" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
		<xs:key name="taskUniq"> <!-- task IDs are unique -->
			<xs:selector xpath="task" />
			<xs:field xpath="@id" />
		</xs:key>
		<xs:key name="communicationUniq"> <!-- communication IDs are unique -->
			<xs:selector xpath="communication" />
			<xs:field xpath="@id" />
		</xs:key>
		<xs:key name="dependencyUniq"> <!-- dependency IDs are unique -->
			<xs:selector xpath="dependency" />
			<xs:field xpath="@id" />
		</xs:key>
	</xs:element>

	<!-- a task models the logical -->
	<xs:element name="task">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attributes" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- a communication models data which is sent by a sending task to one 
		or more receiving tasks -->
	<xs:element name="communication">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attributes" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- a dependency is a directed logical connection between tasks and communications -->
	<xs:element name="dependency">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attributes" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="source" type="xs:string" use="required" />
			<xs:attribute name="destination" type="xs:string" use="required" />
			<xs:attribute name="orientation" use="required"> <!-- orientation of links and dependencies -->
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="DIRECTED" />
						<xs:enumeration value="UNDIRECTED" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<!-- the functions may contain a set of function elements -->
	<xs:element name="functions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="function" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- a function groups tasks and communications -->
	<xs:element name="function">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attributes" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="anchor" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- the mappings element contains at least one mapping for each task -->
	<xs:element name="mappings">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="mapping" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
		<xs:key name="mappingUniq"> <!-- mapping IDs are unique -->
			<xs:selector xpath="mapping" />
			<xs:field xpath="@id" />
		</xs:key>
	</xs:element>

	<!-- a mapping defines on which resource a task could be implemented -->
	<xs:element name="mapping">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attributes" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="source" type="xs:string" use="required" />
			<xs:attribute name="target" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- if existent, the routings element may contain a routing for each communication -->
	<xs:element name="routings">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="routing" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- the routing is given as a directed tree from the resource the sending 
		task is mapped to to all resources, receiving tasks are mapped to -->
	<xs:element name="routing">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="resource" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="link" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="attributes" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="source" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SDARG/opendse/opendse/opendse-tutorial/specs/Implementation7.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns="http://opendse.sourceforge.net"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://opendse.sourceforge.net schema.xsd">
  <architecture>
    <resource id="r2">
      <attributes>
        <attribute name="TYPE" type="STRING">ECU</attribute>
        <attribute name="scheduler" type="STRING">FIXEDPRIORITY_PREEMPTIVE</attribute>
      </attributes>
    </resource>
    <resource id="can">
      <attributes>
        <attribute name="TYPE" type="STRING">CAN</attribute>
        <attribute name="scheduler" type="STRING">FIXEDPRIORITY_NONPREEMPTIVE</attribute>
      </attributes>
    </resource>
    <resource id="r3">
      <attributes>
        <attribute name="TYPE" type="STRING">ECU</attribute>
        <attribute name="scheduler" type="STRING">FIXEDPRIORITY_PREEMPTIVE</attribute>
      </attributes>
    </resource>
    <resource id="r1">
      <attributes>
        <attribute name="TYPE" type="STRING">ECU</attribute>
        <attribute name="scheduler" type="STRING">FIXEDPRIORITY_PREEMPTIVE</attribute>
      </attributes>
    </resource>
    <link id="l1" source="r1" destination="can" orientation="UNDIRECTED"/>
    <link id="l2" source="r2" destination="can" orientation="UNDIRECTED"/>
    <link id="l3" source="r3" destination="can" orientation="UNDIRECTED"/>
  </architecture>
  <application>
    <task id="t4">
      <attributes>
        <attribute name="deadline" type="DOUBLE">4.0</attribute>
        <attribute name="e" type="DOUBLE">1.2</attribute>
        <attribute name="h" type="DOUBLE">5.0</attribute>
      </attributes>
    </task>
    <task id="t5">
      <attributes>
        <attribute name="e" type="DOUBLE">0.5</attribute>
        <attribute name="h" type="DOUBLE">5.0</attribute>
      </attributes>
    </task>
    <task id="t8">
      <attributes>
        <attribute name="e" type="DOUBLE">0.6</attribute>
        <attribute name="h" type="DOUBLE">5.0</attribute>
      </attributes>
    </task>
    <task id="t12">
      <attributes>
        <attribute name="deadline" type="DOUBLE">5.0</attribute>
        <attribute name="e" type="DOUBLE">0.8</attribute>
        <attribute name="h" type="DOUBLE">5.0</attribute>
      </attributes>
    </task>
    <task id="t9">
      <attributes>
        <attribute name="e" type="DOUBLE">0.8</attribute>
        <attribute name="h" type="DOUBLE">5.0</attribute>
      </attributes>
    </task>
    <task id="t1">
      <attributes>
        <attribute name="e" type="DOUBLE">0.8</attribute>
        <attribute name="h" type="DOUBLE">5.0</attribute>
      </attributes>
    </task>
    <task id="t3">
      <attributes>
        <attribute name="deadline" type="DOUBLE">4.0</attribute>
        <attribute name="e" type="DOUBLE">2.0</attribute>
        <attribute name="h" type="DOUBLE">5.0</attribute>
      </attributes>
    </task>
    <communication id="t6">
      <attributes>
        <attribute name="e" type="DOUBLE">0.26</attribute>
        <attribute name="h" type="DOUBLE">5.0</attribute>
      </attributes>
    </communication>
    <communication id="t10">
      <attributes>
        <attribute name="e" type="DOUBLE">0.26</attribute>
        <attribute name="h" type="DOUBLE">5.0</attribute>
      </attributes>
    </communication>
    <communication id="t7">
      <attributes>
        <attribute name="e" type="DOUBLE">0.146</attribute>
        <attribute name="h" type="DOUBLE">5.0</attribute>
      </attributes>
    </communication>
    <communication id="t11">
      <attributes>
        <attribute name="e" type="DOUBLE">0.146</attribute>
        <attribute name="h" type="DOUBLE">5.0</attribute>
      </attributes>
    </communication>
    <communication id="t2">
      <attributes>
        <attribute name="e" type="DOUBLE">0.26</attribute>
        <attribute name="h" type="DOUBLE">5.0</attribute>
      </attributes>
    </communication>
    <dependency id="d-5-7" source="t5" destination="t7" orientation="DIRECTED"/>
    <dependency id="d-5-6" source="t5" destination="t6" orientation="DIRECTED"/>
    <dependency id="d-9-11" source="t9" destination="t11" orientation="DIRECTED"/>
    <dependency id="d-10-12" source="t10" destination="t12" orientation="DIRECTED"/>
    <dependency id="d-8-10" source="t8" destination="t10" orientation="DIRECTED"/>
    <dependency id="d-2-4" source="t2" destination="t4" orientation="DIRECTED"/>
    <dependency id="d-11-12" source="t11" destination="t12" orientation="DIRECTED"/>
    <dependency id="d-2-3" source="t2" destination="t3" orientation="DIRECTED"/>
    <dependency id="d-1-2" source="t1" destination="t2" orientation="DIRECTED"/>
    <dependency id="d-7-9" source="t7" destination="t9" orientation="DIRECTED"/>
    <dependency id="d-6-8" source="t6" destination="t8" orientation="DIRECTED"/>
    <functions>
      <function anchor="t4">
        <attributes>
          <attribute name="ID" type="STRING">func1</attribute>
        </attributes>
      </function>
      <function anchor="t5">
        <attributes>
          <attribute name="ID" type="STRING">func0</attribute>
        </attributes>
      </function>
    </functions>
  </application>
  <mappings>
    <mapping id="m1" source="t1" target="r3"/>
    <mapping id="m3" source="t3" target="r1"/>
    <mapping id="m4" source="t4" target="r2"/>
    <mapping id="m5" source="t5" target="r1"/>
    <mapping id="m8" source="t8" target="r3"/>
    <mapping id="m9" source="t9" target="r3"/>
    <mapping id="m12" source="t12" target="r2"/>
  </mappings>
  <routings>
    <routing source="t6">
      <resource id="can"/>
      <resource id="r3"/>
      <resource id="r1"/>
      <link id="l1" source="r1" destination="can" orientation="DIRECTED"/>
      <link id="l3" source="can" destination="r3" orientation="DIRECTED"/>
    </routing>
    <routing source="t10">
      <resource id="r2"/>
      <resource id="can"/>
      <resource id="r3"/>
      <link id="l2" source="can" destination="r2" orientation="DIRECTED"/>
      <link id="l3" source="r3" destination="can" orientation="DIRECTED"/>
    </routing>
    <routing source="t7">
      <resource id="can"/>
      <resource id="r3"/>
      <resource id="r1"/>
      <link id="l1" source="r1" destination="can" orientation="DIRECTED"/>
      <link id="l3" source="can" destination="r3" orientation="DIRECTED"/>
    </routing>
    <routing source="t11">
      <resource id="r2"/>
      <resource id="can"/>
      <resource id="r3"/>
      <link id="l2" source="can" destination="r2" orientation="DIRECTED"/>
      <link id="l3" source="r3" destination="can" orientation="DIRECTED"/>
    </routing>
    <routing source="t2">
      <resource id="r2"/>
      <resource id="can"/>
      <resource id="r3"/>
      <resource id="r1"/>
      <link id="l1" source="can" destination="r1" orientation="DIRECTED"/>
      <link id="l2" source="can" destination="r2" orientation="DIRECTED"/>
      <link id="l3" source="r3" destination="can" orientation="DIRECTED"/>
    </routing>
  </routings>
</specification>

=== SDARG/opendse/opendse-tutorial/specs/Specification3.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xsi:schemaLocation="http://opendse.sourceforge.net http://opendse.sourceforge.net/schema.xsd" xmlns="http://opendse.sourceforge.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <architecture>
    <resource id="bus1">
      <attributes>
        <attribute name="costs" type="INT">20</attribute>
      </attributes>
    </resource>
    <resource id="bus2">
      <attributes>
        <attribute name="costs" type="INT">20</attribute>
      </attributes>
    </resource>
    <resource id="r1">
      <attributes>
        <attribute name="costs" type="INT">70</attribute>
      </attributes>
    </resource>
    <resource id="r2">
      <attributes>
        <attribute name="costs" type="INT">50</attribute>
      </attributes>
    </resource>
    <resource id="r3"/>
    <link id="l4" source="r2" destination="bus2" orientation="UNDIRECTED"/>
    <link id="l5" source="r3" destination="bus2" orientation="UNDIRECTED"/>
    <link id="l2" source="r2" destination="bus1" orientation="UNDIRECTED"/>
    <link id="l3" source="r1" destination="bus2" orientation="UNDIRECTED"/>
    <link id="l1" source="r1" destination="bus1" orientation="UNDIRECTED"/>
  </architecture>
  <application>
    <task id="t3"/>
    <task id="t2"/>
    <task id="t1"/>
    <task id="t4"/>
    <task id="t5"/>
    <task id="t6"/>
    <communication id="c1"/>
    <communication id="c2"/>
    <communication id="c3"/>
    <dependency id="d1" source="t1" destination="c1" orientation="DIRECTED"/>
    <dependency id="d2" source="c1" destination="t2" orientation="DIRECTED"/>
    <dependency id="d3" source="t3" destination="c2" orientation="DIRECTED"/>
    <dependency id="d5" source="c2" destination="t5" orientation="DIRECTED"/>
    <dependency id="d4" source="c2" destination="t4" orientation="DIRECTED"/>
    <dependency id="d7" source="c3" destination="t6" orientation="DIRECTED"/>
    <dependency id="d6" source="t5" destination="c3" orientation="DIRECTED"/>
    <functions>
      <function anchor="t2">
        <attributes>
          <attribute name="ID" type="STRING">func0</attribute>
        </attributes>
      </function>
      <function anchor="t3">
        <attributes>
          <attribute name="ID" type="STRING">func1</attribute>
        </attributes>
      </function>
    </functions>
  </application>
  <mappings>
    <mapping id="m5" source="t3" target="r3"/>
    <mapping id="m6" source="t4" target="r3"/>
    <mapping id="m7" source="t5" target="r2"/>
    <mapping id="m8" source="t6" target="r1"/>
    <mapping id="m1" source="t1" target="r1"/>
    <mapping id="m2" source="t2" target="r2"/>
    <mapping id="m3" source="t1" target="r3"/>
    <mapping id="m4" source="t2" target="r3"/>
  </mappings>
  <routings>
    <routing source="c1">
      <resource id="bus1"/>
      <resource id="bus2"/>
      <resource id="r1"/>
      <resource id="r2"/>
      <resource id="r3"/>
      <link id="l4" source="r2" destination="bus2" orientation="UNDIRECTED"/>
      <link id="l5" source="r3" destination="bus2" orientation="UNDIRECTED"/>
      <link id="l2" source="r2" destination="bus1" orientation="UNDIRECTED"/>
      <link id="l3" source="r1" destination="bus2" orientation="UNDIRECTED"/>
      <link id="l1" source="r1" destination="bus1" orientation="UNDIRECTED"/>
    </routing>
    <routing source="c2">
      <resource id="bus1"/>
      <resource id="bus2"/>
      <resource id="r1"/>
      <resource id="r2"/>
      <resource id="r3"/>
      <link id="l4" source="r2" destination="bus2" orientation="UNDIRECTED"/>
      <link id="l5" source="r3" destination="bus2" orientation="UNDIRECTED"/>
      <link id="l2" source="r2" destination="bus1" orientation="UNDIRECTED"/>
      <link id="l3" source="r1" destination="bus2" orientation="UNDIRECTED"/>
      <link id="l1" source="r1" destination="bus1" orientation="UNDIRECTED"/>
    </routing>
    <routing source="c3">
      <resource id="bus1"/>
      <resource id="bus2"/>
      <resource id="r1"/>
      <resource id="r2"/>
      <resource id="r3"/>
      <link id="l4" source="r2" destination="bus2" orientation="UNDIRECTED"/>
      <link id="l5" source="r3" destination="bus2" orientation="UNDIRECTED"/>
      <link id="l2" source="r2" destination="bus1" orientation="UNDIRECTED"/>
      <link id="l3" source="r1" destination="bus2" orientation="UNDIRECTED"/>
      <link id="l1" source="r1" destination="bus1" orientation="UNDIRECTED"/>
    </routing>
  </routings>
</specification>

=== SDARG/opendse/opendse/opendse-tutorial/specs/Specification1.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns="http://opendse.sourceforge.net"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://opendse.sourceforge.net schema.xsd"  xmlns:test="http://opendse.sourceforge.net">
  <architecture>
    <resource id="r1">
      <attributes>
        <attribute name="costs" type="INT">100</attribute>
      </attributes>
    </resource>
    <resource id="r2">
      <attributes>
        <attribute name="costs" type="INT">50</attribute>
      </attributes>
    </resource>
    <link id="l1" source="r1" destination="r2" type="UNDIRECTED"/>
  </architecture>
  <application>
    <task id="t2"/>
    <task id="t1"/>
    <dependency id="d1" source="t1" destination="t2" type="DIRECTED"/>
    <functions>
      <function anchor="t2">
        <attributes>
          <attribute name="ID" type="STRING">func0</attribute>
        </attributes>
      </function>
    </functions>
  </application>
  <mappings>
    <mapping id="m1" source="t1" target="r1"/>
    <mapping id="m2" source="t2" target="r2"/>
  </mappings>
  <routings/>
</specification>
